### ISSUE TITLE
Skaled not handled negative numbers in eth_getBlockByNumber method

### ISSUE THREAD

**Issue by gannakulikova** [skalenetwork/skaled#1200]
**Versions**
Skaled: schain:3.14.15-stable.2

**Environment**
20 active nodes on the network
2 schains up and running 

**Steps to Reproduce/Description**
1. Send eth_getBlockByNumber JSON-RPC call to skaled with negative number in params (-1 or -2)
2. check the response

**Expected behavior**
Skaled return the latest mined block if block number is -1 and return the block with empty extra data,  receiptsRoot, sha3Uncles, size, transactions,gasUsed,transactionsRoot and with invalid timestamp, blockHash
Params with  -3 or other numbers return null 

**Actual result** 
skaled should return an error
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 0: hex string without 0x prefix"}}

```
> eth.getBlock(-1)
{
  author: "0xd2ba3e0000000000000000000000000000000000",
  boundary: "0x0000000000000000000000000000000000000000000000000000000000000000",
  difficulty: 0,
  extraData: "0x",
  gasLimit: 268435455,
  gasUsed: 0,
  hash: "0x858c3aa9509168bb8201ff60840073eff0b3da97c676e4f9ae4b0ca2496fbef3",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0xd2ba3e0000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 838466,
  parentHash: "0x0f32234adc96f94bcbc606248c3b75759f722431b4d9fc7dede720a6d2851a12",
  receiptsRoot: "0x0000000000000000000000000000000000000000000000000000000000000000",
  seedHash: "0xc4e19b439d86b4e7cee42d39fbeb4b73364a36cef575d4a7ca649f0869c9d79c",
  sha3Uncles: "0x0000000000000000000000000000000000000000000000000000000000000000",
  size: 0,
  stateRoot: "0xe517d9bbfe206b1c0617e65d05a5b08d60cea70346254b4f410d6b93c19a46c4",
  timestamp: 1666721087,
  totalDifficulty: 0,
  transactions: [],
  transactionsRoot: "0x0000000000000000000000000000000000000000000000000000000000000000",
  uncles: []
}
> eth.getBlock(838466)
{
  author: "0xd2ba3e0000000000000000000000000000000000",
  boundary: "0x0000000000000000000000000000000000000000000000000000000000000000",
  difficulty: 0,
  extraData: "0x736b616c65",
  gasLimit: 268435455,
  gasUsed: 399000,
  hash: "0x964db6c56231b41ca1ded83c420d0570e563e8be3efa3e48a97d8075a9143ad3",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0xd2ba3e0000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 838466,
  parentHash: "0x0f32234adc96f94bcbc606248c3b75759f722431b4d9fc7dede720a6d2851a12",
  receiptsRoot: "0xf318687796f6338d633ca50e904270cab7985439a9bd78ce32ee1e5f4982c6bb",
  seedHash: "0xc4e19b439d86b4e7cee42d39fbeb4b73364a36cef575d4a7ca649f0869c9d79c",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 2588,
  stateRoot: "0xe517d9bbfe206b1c0617e65d05a5b08d60cea70346254b4f410d6b93c19a46c4",
  timestamp: 1666721088,
  totalDifficulty: 0,
  transactions: ["0x28f579d95011541f4bb816f852f91b002993e4d1a403b63ca578d4d1c904ccfe", "0x4d9571a8209bd0b7f0206f606408893c9036498b1b9fbdfce801f6a25f6ac6d7", "0x3b7853b59bc3c9201c201f62b31cfe0356e90723199f232481187ec99cd62bcb", "0xe88f2e24dc3f71c3c4fd17d9e3bde8feb04ec3133120497f7929e2155a7fee1d", "0xe6f5de641e10b9a081fbe03e1800c29d210d103c1b9342850bd4ee8022db45c0", "0x42c287cbd3e79ad680c45e3f733278e6c423c10f973a3863b87bd7d12efdd03a"],
  transactionsRoot: "0x255c0ee0f7074d9552a3de5de12d80bcb0f4ce264e8089c0d5f1cb8193b76404",
  uncles: []
}
```

**Comment by olehnikolaiev** [comment]
not relevant for `3.17.0`
```
> eth.getBlock(-1)
Error: INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised
	at web3.js:6365:9(39)
	at send (web3.js:5099:62(29))
	at <eval>:1:13(4)

> eth.getBlock(0)
{
  author: "0x0000000000000000000000000000000000000001",
  boundary: "0x0000000000000000000000000000000000000000000000000000000000000000",
  difficulty: 0,
  extraData: "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  gasLimit: 268435455,
  gasUsed: 0,
  hash: "0xa5cf2af8bfa86d4dc38bc8afdd76b4c202f5dc4dd6805ff1ffa5b4aba84138f9",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000001",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000abc",
  nonce: "0x0000000000000042",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  seedHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 537,
  stateRoot: "0x66687aadf862bd776c8fc18b8e9f8e20089714856ee233b3902a591d0d5f2925",
  timestamp: 0,
  totalDifficulty: 0,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
```

**Comment by DmytroNazarenko** [comment]
Verified on devnet:
```
> eth.getBlock(-1)
Error: INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised
	at web3.js:6365:9(39)
	at send (web3.js:5099:62(29))
	at <eval>:1:13(4)
```

**Comment by DmytroNazarenko** [comment]
skaled: 3.18.0-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network 
Skale chain aged-wry-finished-skale 
Version skaled: 3.18.0-beta.0

```
curl -X POST --data '{"id":4,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":[-1, false]}'

{'error': {'code': -32602, 'data': None, 'message': 'INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised'}, 'id': 67, 'jsonrpc': '2.0'}
```
