### ISSUE TITLE
Skaled return error if no "from" filed with sFuel in method eth_call

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1284]
**Version**
 
schain:3.14.15-sync.15-historic
schain:3.18.0

**Preconditions**
Active schain medium type.
Address with Sfuel and whitelist deployer role 
Contract to test
 
```
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract MyToken is ERC20 {
    address private owner;
    uint256 private initialBalance;

    event InitialBalance(uint256 balance);
    event AfterInteractionBalance(uint256 balance);
    event BalanceDifference(int256 difference);
    constructor(uint256 _initialSupply) ERC20("MyToken", "MTK") {
        owner = msg.sender;
        _mint(owner, _initialSupply);
        initialBalance = _initialSupply;
        emit InitialBalance(_initialSupply);
    }
    function interact(uint256 _amount) external {
        uint256 balanceBefore = balanceOf(owner);
        transfer(address(0xdeadbeef), _amount);
        uint256 balanceAfter = balanceOf(owner);
        emit AfterInteractionBalance(balanceAfter);
        emit BalanceDifference(int256(balanceAfter) - int256(balanceBefore));
    }
}

```

**To Reproduce**
1. Deploy the contract on the chain and save CONTRACT_ADDRESS (example: ``0x4d9a359786d1d314a0f7363263bf0ed1589152d1``)
data field 
```
0x70a08231 << balanceOf
000000000000000000000000
71cbe3fede33905d4d1bf2bd51f9d4a62375e659 <<< deployer's address to check ERC20 balance 
```
2. send eth_call to the "interact" function without the "from" field via geth attach or JSON-RPC 
example 

```
eth.call({"data":"0x70a0823100000000000000000000000071cbe3fede33905d4d1bf2bd51f9d4a62375e659", "to":"0x4d9a359786d1d314a0f7363263bf0ed1589152d1"},"latest")
```
3. send eth_call to the "interact" function with the field "from" as an account without sFuel via geth attach
```
eth.call({"data":"0x70a0823100000000000000000000000071cbe3fede33905d4d1bf2bd51f9d4a62375e659", "to":"0x4d9a359786d1d314a0f7363263bf0ed1589152d1", "from": 0x79e5b69c1A8E60eC77dc4Ce3b47A9DA8D801a426 },"latest")
```
4. send eth_call to the "interact" function with the field "from" as null
```
eth.call({"data":"0x70a0823100000000000000000000000071cbe3fede33905d4d1bf2bd51f9d4a62375e659", "to":"0x4d9a359786d1d314a0f7363263bf0ed1589152d1", "from": null}, "latest")

```

**Expected behavior**
Eth_call should return the balance of the account 
Example:
``0x0000000000000000000000000000000000000000000000000000000005f5e0fe``

**Actual state:**
Skaled returns the "Account balance is too low" error in steps 2 and 3 on the archival node.

**Logs**
[eth_call_from.log](https://github.com/skalenetwork/skaled/files/10278912/eth_call_from.log)

without from
```
eth.call({"data":"0x00fdd58e000000000000000000000000b04a7f2cd74eb624df4bd8bed8f7034b5aed89c00000000000000000000000000000000000000000000000000000000000000002","to":"0x309180475e7a8de40e6d9f770137d2a680ff1e8e"},1)
Error: Account balance is too low (balance < value + gas * gas price).
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

from account without sFuel:
```
eth.call({"to": "0x693D687ffB22BB2c9dc1E4156D1559D00987dEc8", "data": "0xc1ab22640000000000000000000000000000000000000000000000000000000000000060", "from": "0x88fd5e01078629cc194c933d9631b9448fe10bad"},66544)
Error: Account balance is too low (balance < value + gas * gas price).
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

**Comment by oleksandrSydorenkoJ** [comment]
Actual for schain:3.14.15-sync.18-historic

**Comment by oleksandrSydorenkoJ** [comment]
Version for testing skalenetwork/schain:3.16.0-beta.1-historic

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network
schain:3.16.0-beta.1-historic

without transparent upgradable proxy  

```
eth.call({"data":"0x00fdd58e000000000000000000000000b04a7f2cd74eb624df4bd8bed8f7034b5aed89c00000000000000000000000000000000000000000000000000000000000000002","to":"0x309180475e7a8de40e6d9f770137d2a680ff1e8e"}, 74483)
"0x0000000000000000000000000000000000000000000000000000000000000002"
> eth.call({"data":"0x00fdd58e000000000000000000000000b04a7f2cd74eb624df4bd8bed8f7034b5aed89c00000000000000000000000000000000000000000000000000000000000000002","to":"0x309180475e7a8de40e6d9f770137d2a680ff1e8e"}, 74541)
"0x0000000000000000000000000000000000000000000000000000000000000001"

```

with upgradable proxy:
```
> eth.call({"data":"0x446e847f0000000000000000000000000000000000000000000000000000000000000000","to":"0x5ade1e33ba54081b86c56008866d10688265d43e"},`168505`)
"0x000000000000000000000000309180475e7a8de40e6d9f770137d2a680feeeee"
```

**Comment by EvgeniyZZ** [comment]
Retest on 3.16.0-beta.2

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network
Schain name: troubled-tall-rotanev

skalenetwork/schain:3.16.0-beta.3-historic


without from:
```

> eth.call({"data":"0x446e847f0000000000000000000000000000000000000000000000000000000000000000","to":"0x5ade1e33ba54081b86c56008866d10688265d43e"}, '168568')
"0x000000000000000000000000309180475e7a8de40e6d9f770137d2a680feeeee"
```

with address without balance:
```
> eth.call({"data":"0x446e847f0000000000000000000000000000000000000000000000000000000000000000", "from":"0x5ade1e33ba54081b86c56008866d10688265d43e", "to":"0x5ade1e33ba54081b86c56008866d10688265d43e"}, '168568')
"0x000000000000000000000000309180475e7a8de40e6d9f770137d2a680feeeee"
```
with admin address:
```
> eth.call({"data":"0x446e847f0000000000000000000000000000000000000000000000000000000000000000", "from":"0x0000000000000000000000000000000000000000", "to":"0x5ade1e33ba54081b86c56008866d10688265d43e"}, '168568')
"0x000000000000000000000000309180475e7a8de40e6d9f770137d2a680feeeee"

```
