### ISSUE TITLE
Skaled return an error if block contains more than 1 transaction from single user for debug traceBlockByNumber

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1751]
**Preconditions**
Active chains
Archival node
Deployed contract with erc20 tokens

**Versions**
skalenetwork/schain:3.17.2-develop.2-historic

**Steps to reproduce**

1. Send several transactions into the same block from 1 user
2. Send debug.traceBlockByNumber method

**Expected state**:
Skaled should return the tracing result by executing all transactions in the block specified by number with a tracer

**Actual state**:
Skaled returns the error:
```
> debug.traceBlockByNumber('0x1dcc5', {"tracer": "callTracer"})
Error: State check failed::m_topFunctionCall /home/gha/actions-runner-1/_work/skaled/skaled/libhistoric/AlethStandardTrace.cpp:354
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

{
  author: "0xd2ba3e0000000000000000000000000000000000",
  boundary: "0x0000000000000000000000000000000000000000000000000000000000000000",
  difficulty: 0,
  extraData: "0x736b616c65",
  gasLimit: 268435455,
  gasUsed: 106000,
  hash: "0x5d58670136d034b8598d10dcf77b9c11a81db21143946f4956407a5c2c2af7cb",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0xd2ba3e0000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 122053,
  parentHash: "0xb50016280550d3a235e2a69701b18eb9d59b5c5901b7cde97a3bbfb61ac9e354",
  receiptsRoot: "0xbf3582ecd042451d77a3e737882a790c96b287b9a96965330d7af0fc32e652ff",
  seedHash: "0xb903bd7696740696b2b18bd1096a2873bb8ad0c2e7f25b00a0431014edb3f539",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 675,
  stateRoot: "0x10082ac6d6578a7bb98227684ecd99753eea170eda7ada82144def92709620ff",
  timestamp: 1702405860,
  totalDifficulty: 0,
  transactions: ["0x0801c1ca24dee92ddef3594205f1cda1895e21312d285c9557b179c1d8c81fb3", "0x7d7a60dee54595e288ea1880ec107a811a3f24444ff804950af45ca04f32f90f"],
  transactionsRoot: "0x4e3b6310f238729194ab017e99b0e23aeb722f8c172f6af078ef691dead96086",
  uncles: []
}


```

```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/skaled/issues/1750
```

**Comment by oleksandrSydorenkoJ** [comment]
The same behavior for traceBlockByHash
```
> debug.traceBlockByHash('0x5d58670136d034b8598d10dcf77b9c11a81db21143946f4956407a5c2c2af7cb', {"tracer": "callTracer"})
Error: State check failed::m_topFunctionCall /home/gha/actions-runner-1/_work/skaled/skaled/libhistoric/AlethStandardTrace.cpp:354
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

**Comment by PolinaKiporenko** [comment]
3.18.1-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
Verified on legacy network
skale_schain_these-long-sadalsuud
skalenetwork/schain:3.18.1-beta.0-historic
Block 299928 

```
 curl http://localhost:10195/   -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceBlockByHash","params":["0x25cff663ed8a437c73ffbf24b736e5880cca43b9e73242455de837afd1ec3ae6", {"tracer": "callTracer"}], "id":1,"jsonrpc":"2.0"}'
{"id":1,"jsonrpc":"2.0","result":[{"result":{"from":"0xe3cc6ec63b5652d1594bc63bb293f4e80f76dbdd","gas":"0x186a0","gasUsed":"0xbee2","input":"0x40c10f19000000000000000000000000e3cc6ec63b5652d1594bc63bb293f4e80f76dbdd00000000000000000000000000000000000000000000000000038d7ea4c68000","to":"0xa63857527ad8a8114e091480accea02d410bfe7b","type":"CALL","value":"0x0"},"txHash":"0xf9429ce366fc27e4c2dabdd87056c076ffe7612b281280493b2a5381f5179caa"},{"result":{"from":"0x0aa6a44690ef52354e976990292cf9c5cd36ad59","gas":"0x186a0","gasUsed":"0xbee2","input":"0x40c10f190000000000000000000000000aa6a44690ef52354e976990292cf9c5cd36ad5900000000000000000000000000000000000000000000000000038d7ea4c68000","to":"0xa63857527ad8a8114e091480accea02d410bfe7b","type":"CALL","value":"0x0"},"txHash":"0x5d213ad95e7d59766f095187bb9191ba1ccbfdc5ed90f601872f4b61044dba5b"},{"result":{"from":"0x77a0bc73442d3d9cb993e8d9752f95babf0ccaa6","gas":"0x186a0","gasUsed":"0xbee2","input":"0x40c10f1900000000000000000000000077a0bc73442d3d9cb993e8d9752f95babf0ccaa600000000000000000000000000000000000000000000000000038d7ea4c68000","to":"0xa63857527ad8a8114e091480accea02d410bfe7b","type":"CALL","value":"0x0"},"txHash":"0xc1df48a38cce383656788021413810c778381ef86bd6465976fe6fb70268066b"},{"result":{"from":"0xa68f946090c600eda6f139783077ee802afeb990","gas":"0x186a0","gasUsed":"0xbed6","input":"0x40c10f19000000000000000000000000a68f946090c600eda6f139783077ee802afeb99000000000000000000000000000000000000000000000000000038d7ea4c68000","to":"0xa63857527ad8a8114e091480accea02d410bfe7b","type":"CALL","value":"0x0"},"txHash":"0xea028b9a39fc01ba516bb921a229d662c6bae67fb694a8f7b2193b0aaf6ea847"},{"result":{"from":"0x94c6e5746971d6aebeaa42cbbe2feca0f6b5b24f","gas":"0x186a0","gasUsed":"0xbee2","input":"0x40c10f1900000000000000000000000094c6e5746971d6aebeaa42cbbe2feca0f6b5b24f00000000000000000000000000000000000000000000000000038d7ea4c68000","to":"0xa63857527ad8a8114e091480accea02d410bfe7b","type":"CALL","value":"0x0"},"txHash":"0xcb4e1a23edc869634323625eba99a441d3a183fcb25a3debc8be733c822f4f35"},{"result":{"from":"0x3f5bdf5d4c274c82b8d17aa2810b00d2cf050f24","gas":"0x186a0","gasUsed":"0xbed6","input":"0x40c10f190000000000000000000000003f5bdf5d4c274c82b8d17aa2810b00d2cf050f2400000000000000000000000000000000000000000000000000038d7ea4c68000","to":"0xa63857527ad8a8114e091480accea02d410bfe7b","type":"CALL","value":"0x0"},"txHash":"0x472c7e47150534ede01862918f489c87e755f621fb730b57cca60b7f83f5746d"},{"result":{"from":"0x863f816036e3cbba90855196c9d1e339fcff1650","gas":"0x186a0","gasUsed":"0xbee2","input":"0x40c10f19000000000000000000000000863f816036e3cbba90855196c9d1e339fcff165000000000000000000000000000000000000000000000000000038d7ea4c68000","to":"0xa63857527ad8a8114e091480accea02d410bfe7b","type":"CALL","value":"0x0"},"txHash":"0x35341c96c0b5361709cce0558ef3c9c262575d31be9d9db054a26c8c6f552058"},{"result":{"from":"0x88fd5e01078629cc194c933d9631b9448fe10b1d","gas":"0x186a0","gasUsed":"0xbee2","input":"0x40c10f1900000000000000000000000088fd5e01078629cc194c933d9631b9448fe10b1d00000000000000000000000000000000000000000000000000038d7ea4c68000","to":"0xa63857527ad8a8114e091480accea02d410bfe7b","type":"CALL","value":"0x0"},"txHash":"0x06506035980c648205ed7489f921ad85850eb25e751a71390116b11da45f2bb0"}]}
```
