### ISSUE TITLE
tracing test fails

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skaled#1949]
tracing api test fails when running `npx hardhat run scripts/trace.ts --network skaled` with the following error

```npx hardhat run scripts/trace.ts --network skaled
Directory recreated: /tmp/skale_traces/
Deploying Tracer
Contract deployed to 0x4814cFEf88B9ee06a2d56925F5fCc554045eA53a at block 2 tx hash 0xaef5f492b8d5db4fa167e7eb1b337c2fd226361f247c0823e9c2b3ebcb054a3e
Address: 0xe8E00e21aDB05De25208ac48B034F22cf2479F3E
Submitted a tx to send 0.1 ETH to 0xe8E00e21aDB05De25208ac48B034F22cf2479F3E
Calling debug_traceTransaction to generate Tracer.deploy.defaultTracer.json
Calling debug_traceTransaction to generate Tracer.deploy.callTracer.json
Calling debug_traceTransaction to generate Tracer.deploy.4byteTracer.json
Calling debug_traceTransaction to generate Tracer.deploy.prestateDiffTracer.json
Calling debug_traceTransaction to generate Tracer.deploy.prestateTracer.json
Calling debug_traceTransaction to generate Tracer.mint.defaultTracer.json
Calling debug_traceTransaction to generate Tracer.mint.callTracer.json
Calling debug_traceTransaction to generate Tracer.mint.prestateTracer.json
Calling debug_traceTransaction to generate Tracer.mint.prestateDiffTracer.json
Calling debug_traceTransaction to generate Tracer.mint.4byteTracer.json
Address: 0xF169AaF96Dd8a30f910a95fd04d9B6D2eF034D6d
Submitted a tx to send 0.1 ETH to 0xF169AaF96Dd8a30f910a95fd04d9B6D2eF034D6d
Calling debug_traceTransaction to generate Tracer.transfer.defaultTracer.json
Calling debug_traceTransaction to generate Tracer.transfer.callTracer.json
Calling debug_traceTransaction to generate Tracer.transfer.prestateTracer.json
Calling debug_traceTransaction to generate Tracer.transfer.prestateDiffTracer.json
Calling debug_traceTransaction to generate Tracer.transfer.4byteTracer.json
Calling debug_traceTransaction to generate Tracer.mint2.defaultTracer.json
Calling debug_traceTransaction to generate Tracer.mint2.callTracer.json
Calling debug_traceTransaction to generate Tracer.mint2.prestateTracer.json
Calling debug_traceTransaction to generate Tracer.mint2.prestateDiffTracer.json
Calling debug_traceTransaction to generate Tracer.mint2.4byteTracer.json
Calling debug_traceTransaction to generate Tracer.readableRevert.defaultTracer.json
Calling debug_traceTransaction to generate Tracer.readableRevert.callTracer.json
Calling debug_traceTransaction to generate Tracer.readableRevert.prestateTracer.json
Calling debug_traceTransaction to generate Tracer.readableRevert.prestateDiffTracer.json
Calling debug_traceTransaction to generate Tracer.readableRevert.4byteTracer.json
Calling debug_traceCall to generate  Tracer.getBalance.defaultTracer.json
ProviderError: tracing_traceCall:237:Could not execute historic call for transactionIndex:0:Exception doing trace for transaction index:0:State check failed::_gasUsed < std::numeric_limits< uint32_t >::max() /home/oleh/work/skaled_historic/skaled/libhistoric/FunctionCallRecord.cpp:35
    at HttpProvider.request (/home/oleh/work/skaled_historic/skaled/test/historicstate/hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:96:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EthersProviderWrapper.send (/home/oleh/work/skaled_historic/skaled/test/historicstate/hardhat/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
    ```

**Comment by PolinaKiporenko** [comment]
still relevant
