### ISSUE TITLE
sChain couldn't start after recovery

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/skaled#409]
sChain version: v2.0.0-beta.0
sChain couldn't start after recovery

**Recovery steps:**
1. We create 16-node MEDIUM sChain
2. Stopping sChain container on 6 nodes one-by-one (10/16 working -> block mining is stopped) 
3. Restart one of stopped containers  (11/16 working)

**Expected:**
sChain continue block mining

**Got:**
sChain doesn't mine blocks after 11 nodes are working

**STR:**
Run  recovery test  from skale-test-cli. Logs from failed test below

┆Attachments: <a href="https://skalelabs.atlassian.net/secure/attachment/10466/becrux.txt">becrux.txt</a> | <a href="https://skalelabs.atlassian.net/secure/attachment/10358/noisy-gorgonea-secunda.zip">noisy-gorgonea-secunda.zip</a> | <a href="https://skalelabs.atlassian.net/secure/attachment/10383/rapping-angetenar.zip">rapping-angetenar.zip</a>

**Comment by cstrangedk** [comment]
➤ Dmytro Nazarenko commented:

Seems like 11-th node couldn’t start after restart, because couldn’t connect to nodes. Evgeniy Zherdzitskiy can add

**Comment by cstrangedk** [comment]
➤ Dmytro Nazarenko commented:

Also couldn’t stop schain gracefully on some nodes(timeout = 180s): 52.58.225.67, 3.124.196.62

**Comment by cstrangedk** [comment]
➤ Dima Litvinov commented:

Dmytro Nazarenko which node was 11th? I want to look into its logs.
aha, looks like it’s 18.185.113.81 - will check

**Comment by cstrangedk** [comment]
➤ Stan Kladko commented:

For this node - did you kill it or did you let it stop gracefully ?)

**Comment by cstrangedk** [comment]
➤ Dmytro Nazarenko commented:

I give it 180s to stop, it stops in 15s - so it stops normally. You can take a look in test log above - it has steps with timestamps

**Comment by cstrangedk** [comment]
➤ Ganna Kulikova commented:

Not critical for the release

**Comment by cstrangedk** [comment]
➤ Ganna Kulikova commented:

Should be re-verified with the recent skaled and consensus fixes - Evgeniy Zherdzitskiy

**Comment by cstrangedk** [comment]
➤ Dmytro Nazarenko commented:

skaled version: 2.0.4-develop.3
status: reproducible
testing logs:

====================================================================================================
test: Recover sChain after insufficient node amount
sChain type: SMALL
Downtime: 120
No cleanup: True
====================================================================================================

[2020-11-26 14:05:01,587 INFO] core.nodes - MainThread - Initializing nodes. Active nodes: 16
[2020-11-26 14:05:01,823 INFO] skale.contracts.manager.manager - MainThread - create_schain: type_of_nodes: 1, name: rapping-angetenar
[2020-11-26 14:05:01,830 INFO] skale.transactions.tools - MainThread - Dry run tx: send, sender: 0xA9C3F6D35fE2BeDf4DdA3B8f9625cf0652AEbEAa, wallet: Web3Wallet, gasLimit: 10000000
[2020-11-26 14:05:01,959 INFO] skale.transactions.tools - MainThread - Tx: send, sender: 0xA9C3F6D35fE2BeDf4DdA3B8f9625cf0652AEbEAa, wallet: Web3Wallet, gasLimit: 10000000, gasPrice: 50000000000
[2020-11-26 14:05:35,561 INFO] core.manager.schains - MainThread - sChain rapping-angetenar successfully created
[2020-11-26 14:07:05,440 INFO] tools.checks - MainThread - Wait successful check_schain_alive for 49s ...
[2020-11-26 14:08:05,144 INFO] tools.checks - MainThread - Wait successful check_schain_alive for 109s ...
[2020-11-26 14:09:05,801 INFO] tools.checks - MainThread - Wait successful check_schain_alive for 170s ...
[2020-11-26 14:09:59,356 INFO] tools.checks - MainThread - ✔ check_schain_alive is succeed
[2020-11-26 14:09:59,357 INFO] core.infrastructure.instances - MainThread - Node: 34.244.197.165 - Stopping skale_schain_rapping-angetenar container...
[2020-11-26 14:13:01,376 INFO] core.infrastructure.instances - MainThread - Node: 34.253.0.184 - Stopping skale_schain_rapping-angetenar container...
[2020-11-26 14:13:11,815 INFO] core.infrastructure.instances - MainThread - Node: 34.242.29.35 - Stopping skale_schain_rapping-angetenar container...
[2020-11-26 14:13:21,937 INFO] core.infrastructure.instances - MainThread - Node: 34.248.12.186 - Stopping skale_schain_rapping-angetenar container...
[2020-11-26 14:16:23,904 INFO] core.infrastructure.instances - MainThread - Node: 54.155.175.229 - Stopping skale_schain_rapping-angetenar container...
[2020-11-26 14:16:34,910 INFO] core.infrastructure.instances - MainThread - Node: 3.248.232.192 - Stopping skale_schain_rapping-angetenar container...
[2020-11-26 14:19:37,094 INFO] tests.schains_tests - MainThread - Less than minimum sufficient amount of nodes is working
[2020-11-26 14:20:18,941 INFO] tests.schains_tests - MainThread - ✔ sChain RPC is working
[2020-11-26 14:20:18,941 INFO] tests.schains_tests - MainThread - Sleep 120s
[2020-11-26 14:20:18,942 INFO] core.infrastructure.instances - MainThread - Node: 3.248.232.192 - Restarting skale_schain_rapping-angetenar container...
[2020-11-26 14:21:03,313 INFO] tools.checks - MainThread - ✔ check_schain_alive is succeed
[2020-11-26 14:21:46,872 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 0s ...
[2020-11-26 14:21:57,039 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 10s ...
[2020-11-26 14:22:07,230 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 20s ...
[2020-11-26 14:22:17,407 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 30s ...
[2020-11-26 14:22:27,587 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 40s ...
[2020-11-26 14:22:37,749 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 51s ...
[2020-11-26 14:22:47,934 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 61s ...
[2020-11-26 14:22:58,111 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 71s ...
[2020-11-26 14:23:08,299 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 81s ...
[2020-11-26 14:23:18,475 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 91s ...
[2020-11-26 14:23:28,660 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 101s ...
[2020-11-26 14:23:38,849 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 112s ...
[2020-11-26 14:23:49,032 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 122s ...
[2020-11-26 14:23:59,208 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 132s ...
[2020-11-26 14:24:09,415 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 142s ...
[2020-11-26 14:24:19,612 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 152s ...
[2020-11-26 14:24:29,804 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 163s ...
[2020-11-26 14:24:39,999 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 173s ...
[2020-11-26 14:24:50,176 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 183s ...
[2020-11-26 14:25:00,341 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 193s ...
[2020-11-26 14:25:10,522 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 203s ...
[2020-11-26 14:25:20,704 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 213s ...
[2020-11-26 14:25:30,879 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 224s ...
[2020-11-26 14:25:41,042 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 234s ...
[2020-11-26 14:25:51,239 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 244s ...
[2020-11-26 14:26:01,417 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 254s ...
[2020-11-26 14:26:11,587 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 264s ...
[2020-11-26 14:26:21,764 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 275s ...
[2020-11-26 14:26:31,939 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 285s ...
[2020-11-26 14:26:42,113 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 295s ...
[2020-11-26 14:26:52,290 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 305s ...
[2020-11-26 14:27:02,473 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 315s ...
[2020-11-26 14:27:12,679 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 325s ...
[2020-11-26 14:27:22,860 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 336s ...
[2020-11-26 14:27:33,045 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 346s ...
[2020-11-26 14:27:43,234 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 356s ...
[2020-11-26 14:27:53,415 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 366s ...
[2020-11-26 14:28:03,629 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 376s ...
[2020-11-26 14:28:13,816 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 387s ...
[2020-11-26 14:28:23,977 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 397s ...
^[[A^[[A[2020-11-26 14:28:34,155 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 407s ...
[2020-11-26 14:28:44,326 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 417s ...
[2020-11-26 14:28:54,487 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 427s ...
[2020-11-26 14:29:04,658 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 437s ...
[2020-11-26 14:29:14,846 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 448s ...
[2020-11-26 14:29:25,023 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 458s ...
[2020-11-26 14:29:35,202 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 468s ...
[2020-11-26 14:29:45,396 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 478s ...
[2020-11-26 14:29:55,563 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 488s ...
[2020-11-26 14:30:05,735 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 499s ...
[2020-11-26 14:30:15,910 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 509s ...
[2020-11-26 14:30:26,089 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 519s ...
[2020-11-26 14:30:36,258 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 529s ...
[2020-11-26 14:30:46,420 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 539s ...
[2020-11-26 14:30:56,610 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 549s ...
[2020-11-26 14:31:06,784 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 560s ...
[2020-11-26 14:31:16,981 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 570s ...
[2020-11-26 14:31:27,185 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 580s ...
[2020-11-26 14:31:37,377 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 590s ...
[2020-11-26 14:31:47,547 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 600s ...
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    cmd_collection()
  File "/home/rikon/dev/integration_tests_for_node-rotation/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rikon/dev/integration_tests_for_node-rotation/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rikon/dev/integration_tests_for_node-rotation/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rikon/dev/integration_tests_for_node-rotation/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rikon/dev/integration_tests_for_node-rotation/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rikon/dev/integration_tests_for_node-rotation/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rikon/dev/integration_tests_for_node-rotation/cli/schains_tests.py", line 125, in schain_recovery_cli
    test_schain_recovery(type, downtime, no_cleanup)
  File "/home/rikon/dev/integration_tests_for_node-rotation/tests/schains_tests.py", line 165, in test_schain_recovery
    check_schain_mining(schain['name'], alive_node.id)
  File "/home/rikon/dev/integration_tests_for_node-rotation/tools/checks.py", line 130, in check_schain_mining
    check_for_new_blocks(web3, last_block_number)
  File "/home/rikon/dev/integration_tests_for_node-rotation/tools/checks.py", line 30, in wrapper
    assert delta_time < timeout
AssertionError
[2020-11-26 14:31:57,746 ERROR] __main__ - MainThread - scain logs:

[^rapping-angetenar.zip]

**Comment by cstrangedk** [comment]
➤ Ganna Kulikova commented:

Potentially caused by https://skalelabs.atlassian.net/browse/SKALE-3400 ( https://skalelabs.atlassian.net/browse/SKALE-3400|smart-link )

**Comment by cstrangedk** [comment]
➤ Stan Kladko commented:

Moving To QA as this may be fixed by recent changes.

**Comment by cstrangedk** [comment]
➤ Dmytro Nazarenko commented:

Still reproducible for 3.2.0-develop.0
sChain logs:

[2020-12-11 13:38:53.218] [0:main] [info] 318:Consensus exiting: Node:Exit requested
[2020-12-11 13:38:53.218] [0:main] [info] 318:Consensus exiting: Node:Exit requested
thread before exit
[2020-12-11 13:38:53.218] [config] [info] Cleaning up ZMQ sockets
[2020-12-11 13:38:53.219] [config] [info] Closing ZMQ context
[2020-12-11 13:38:53.220] [config] [info] Closed ZMQ
thread after exit
3 after wait loop
4 before dtor
nodes.clear()!!
2020-12-11 13:39:02.433287   Blockchain is closed
2020-12-11 13:39:02.433605   Blockchain is closed
.

skaled 3.2.0+commit.45b72a78

This process PID=1
Dispatch: Have all 16 threads in pool started fast
btrfs filesystem df /data_dir
btrfs filesystem df /data_dir/28e07f34
btrfs subvolume create /data_dir/28e07f34
btrfs filesystem df /data_dir/filestorage
btrfs subvolume create /data_dir/filestorage
btrfs filesystem df /data_dir/prices_0.db
btrfs subvolume create /data_dir/prices_0.db
btrfs filesystem df /data_dir/blocks_0.db
btrfs subvolume create /data_dir/blocks_0.db
2020-12-11 13:39:46.071469   Important notce: Programmatic enable-debug-behavior-apis mode is enabled
2020-12-11 13:39:46.071544   Important notce: Programmatic unsafe-transactions mode is disabled
2020-12-11 13:39:46.071573   Important notce: Programmatic web3-shutdown mode is disabled
2020-12-11 13:39:46.071622   DB path is: /data_dir
skaled, a C++ Skale client
2020-12-11 13:39:46.162718   Removing flag file /skale_schain_data/.rotation
2020-12-11 13:39:46.425481   Snapshots enabled, snapshotIntervalSec is: 300
2020-12-11 13:39:46.425789   Latest snapshots init: 0 159 -> 0
2020-12-11 13:39:46.425823   Fake Last snapshot creation time: 1607693700
NOTE: Block number at startup is 318
Consensus engine version:1.61.1
Found data dir:/data_dir
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:10981389590094055437098462878264523823260196486476346195209766001870865782151
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:1598400192515239742781213988674771837243344752502498261198933097803456286838
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:4942437117182657765951729084505664261993893136683564636321983979799816104988
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:21060470873727775336605441886362036407371371910542296865304786282339345623086
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:14339888808303948928450910304557396801867653056411225607097013311096384727062
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:18152702811437433834609773922261830240149881489485904616198705605935640546769
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:12943671198423327429052931602297743892277039620713588450442553200272004924683
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:831663628884553684275399492377751533406793633576462867742209639331779173246
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:20372970511503763413525711447723172338111052349460965097719217276387457692112
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:6919978517528049983857776611696771145339451581013963028350584801930995016151
[2020-12-11 13:39:46.442] [config] [info] Parsing BLS key share:8836524340639972688396140368101946891817540546793230638748608757026876513650
[2020-12-11 13:39:46.516] [config] [info] Monitoring agent started monitoring
[2020-12-11 13:39:46.518] [0:main] [info] 0:Setting sgxSSLKeyFileFullPath to /skale_node_data/sgx_certs/sgx.key
[2020-12-11 13:39:46.518] [0:main] [info] 0:Setting sgxCertKeyFileFullPath to /skale_node_data/sgx_certs/sgx.crt
[2020-12-11 13:39:46.518] [0:main] [info] 0:Getting ECDSA public key for NEK:39738ae8799fadc02ba71c7bb4e1021b4b6bab5882a41d689107667bc606c859
[2020-12-11 13:39:46.671] [0:main] [info] 0:Got ECDSA public key: 01655353ce8cc025c50404e03583da541ca0c31117f43ffb76a94d532411034d045c76e93596548861f4dbd116f5d7599b857ff8baae37cd1a676588b9228abd
Starting consensus engine ...[2020-12-11 13:39:48.416] [0:main] [info] 0:Starting node
tcp://54.74.158.74:10005
tcp://34.244.96.30:10005
tcp://34.244.197.165:10005
tcp://34.240.153.172:10005
tcp://54.155.175.229:10005
tcp://54.171.237.108:10005
tcp://3.248.232.192:10005
tcp://54.154.226.7:10005
tcp://34.247.92.193:10005
tcp://3.248.233.34:10005
tcp://34.248.12.186:10005
tcp://34.253.0.184:10005
tcp://34.247.73.22:10005
tcp://3.248.204.16:10005
tcp://54.74.232.23:10005
[2020-12-11 13:39:48.419] [0:consensus] [info] 0:Started servers0
[2020-12-11 13:39:48.438] [0:main] [info] 0:Waiting to connect to peers
[2020-12-11 13:39:54.464] [0:main] [info] 0:Successfully connected to two thirds of peers
[2020-12-11 13:39:54.464] [0:consensus] [info] 0:Started clients0
[2020-12-11 13:39:54.464] [0:consensus] [info] 0:Started all nodes
[2020-12-11 13:39:54.464] [config] [info] Bootstrapping consensus ...
[2020-12-11 13:39:54.464] [config] [info] Check the consensus database for corruption ...
[2020-12-11 13:39:54.464] [config] [info] Last committed block in consensus:318
[2020-12-11 13:39:54.465] [config] [info] Jump starting the system with block:318
[2020-12-11 13:39:54.528] [config] [info] BIN_CONSENSUS_START: PROPOSING: 0000000000000000
[2020-12-11 13:39:54.742] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.155.175.229:10000:Connection refused
[2020-12-11 13:39:54.742] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.96.30:10000:Connection refused
[2020-12-11 13:39:54.742] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.240.153.172:10000:Connection refused
[2020-12-11 13:39:54.742] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.74.158.74:10000:Connection refused
[2020-12-11 13:39:54.743] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.197.165:10000:Connection refused
[2020-12-11 13:39:54.743] [config] [info] Rebroadcasting messages for the current block
Mining Beneficiary: a9c3f6d35fe2bedf4dda3b8f9625cf0652aebeaa
2020-12-11 13:39:57.804362   IPv6 bind address is not set, will not start RPC on this protocol
Reload configuration file Loading configuration from /skale_schain_data/schain_fit-auva.json ... 
Reload configuration file Parsing configuration JSON ... 
Reload configuration file Done, loaded configuration file /skale_schain_data/schain_fit-auva.json
2020-12-11 13:39:57.865366   JSONRPC Admin Session Key: pM0YUCeLPJc=
[2020-12-11 13:40:04.465] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.74.158.74:10001:Connection refused
[2020-12-11 13:40:14.466] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.96.30:10001:Connection refused
[2020-12-11 13:40:24.467] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.197.165:10001:Connection refused
[2020-12-11 13:40:34.468] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.240.153.172:10001:Connection refused
[2020-12-11 13:40:44.469] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.155.175.229:10001:Connection refused
[2020-12-11 13:41:54.550] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:43:54.607] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:45:54.659] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:47:54.713] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:49:54.768] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:49:54.910] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.155.175.229:10000:Connection refused
[2020-12-11 13:49:54.910] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.96.30:10000:Connection refused
[2020-12-11 13:49:54.910] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.74.158.74:10000:Connection refused
[2020-12-11 13:49:54.910] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.197.165:10000:Connection refused
[2020-12-11 13:49:54.910] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.240.153.172:10000:Connection refused
[2020-12-11 13:50:04.578] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.74.158.74:10001:Connection refused
[2020-12-11 13:50:14.579] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.96.30:10001:Connection refused
[2020-12-11 13:50:24.579] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.197.165:10001:Connection refused
[2020-12-11 13:50:34.580] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.240.153.172:10001:Connection refused
[2020-12-11 13:50:44.581] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.155.175.229:10001:Connection refused
[2020-12-11 13:51:54.822] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:53:54.876] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:55:54.929] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:57:54.984] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:59:55.041] [config] [info] Rebroadcasting messages for the current block
[2020-12-11 13:59:55.075] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.240.153.172:10000:Connection refused
[2020-12-11 13:59:55.075] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.155.175.229:10000:Connection refused
[2020-12-11 13:59:55.075] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.197.165:10000:Connection refused
[2020-12-11 13:59:55.075] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.74.158.74:10000:Connection refused
[2020-12-11 13:59:55.076] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.96.30:10000:Connection refused
[2020-12-11 14:00:04.696] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.74.158.74:10001:Connection refused
[2020-12-11 14:00:14.697] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.96.30:10001:Connection refused
[2020-12-11 14:00:24.698] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.244.197.165:10001:Connection refused
[2020-12-11 14:00:34.699] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:34.240.153.172:10001:Connection refused
[2020-12-11 14:00:44.700] [0:main] [error] 318:!Exception: ClientSocket:Couldnt connect to:54.155.175.229:10001:Connection refused
[2020-12-11 14:01:55.096] [config] [info] Rebroadcasting messages for the current blockSGX logs:

2020-12-11T14:01:34.805659858Z  number of ca found  in /usr/src/sdk/sgx_data/cert_data is 2
2020-12-11T14:01:34.806042686Z client cert is verified with status 2050
2020-12-11T14:01:34.806081633Z client cert is not verified
2020-12-11T14:01:34.806095133Z no cert
2020-12-11T14:02:12.346274174Z  number of ca found  in /usr/src/sdk/sgx_data/cert_data is 2
2020-12-11T14:02:12.346677463Z client cert is verified with status 2050
2020-12-11T14:02:12.346727259Z client cert is not verified
2020-12-11T14:02:12.346742842Z no cert
2020-12-11T14:02:35.685741644Z  number of ca found  in /usr/src/sdk/sgx_data/cert_data is 2
2020-12-11T14:02:35.686211566Z client cert is verified with status 2050
2020-12-11T14:02:35.686248034Z client cert is not verified
2020-12-11T14:02:35.686261734Z no cert
2020-12-11T14:03:36.548213189Z  number of ca found  in /usr/src/sdk/sgx_data/cert_data is 2
2020-12-11T14:03:36.548621346Z client cert is verified with status 2050
2020-12-11T14:03:36.548658695Z client cert is not verified
2020-12-11T14:03:36.548672178Z no cert
2020-12-11T14:04:18.350367052Z  number of ca found  in /usr/src/sdk/sgx_data/cert_data is 2
2020-12-11T14:04:18.350761074Z client cert is verified with status 2050
2020-12-11T14:04:18.350806635Z client cert is not verified
2020-12-11T14:04:18.350825562Z no cert
2020-12-11T14:04:37.407108197Z  number of ca found  in /usr/src/sdk/sgx_data/cert_data is 2
2020-12-11T14:04:37.407510598Z client cert is verified with status 2050
2020-12-11T14:04:37.407547675Z client cert is not verified
2020-12-11T14:04:37.407568253Z no cert
2020-12-11T14:05:38.351047373Z  number of ca found  in /usr/src/sdk/sgx_data/cert_data is 2
2020-12-11T14:05:38.351458515Z client cert is verified with status 2050
2020-12-11T14:05:38.351497338Z client cert is not verified
2020-12-11T14:05:38.351511578Z no cert

**Comment by cstrangedk** [comment]
➤ Dmytro Nazarenko commented:

Certificates not found for 11-th node

**Comment by cstrangedk** [comment]
➤ Dmytro Nazarenko commented:

Certificate issue was caused by old node on AWS

**Comment by cstrangedk** [comment]
➤ Dmytro Nazarenko commented:

[^becrux.txt]

[2020-12-21 19:20:49,849 INFO] tests.schains_tests - MainThread - 
====================================================================================================
test: Recover sChain after insufficient node amount
sChain type: SMALL
Downtime: 120
No cleanup: True
====================================================================================================

[2020-12-21 19:20:54,165 INFO] core.nodes - MainThread - Initializing nodes. Active nodes: 16
[2020-12-21 19:20:54,672 INFO] skale.contracts.manager.manager - MainThread - create_schain: type_of_nodes: 1, name: whispering-becrux
[2020-12-21 19:20:54,717 INFO] skale.transactions.tools - MainThread - Dry run tx: send, sender: 0xA9C3F6D35fE2BeDf4DdA3B8f9625cf0652AEbEAa, wallet: Web3Wallet, 
[2020-12-21 19:20:55,830 INFO] skale.transactions.tools - MainThread - Estimated gas for send: 9280257
[2020-12-21 19:20:55,909 INFO] skale.transactions.tools - MainThread - Tx: send, sender: 0xA9C3F6D35fE2BeDf4DdA3B8f9625cf0652AEbEAa, wallet: Web3Wallet, gasLimit: 9280257, gasPrice: 50000000000
[2020-12-21 19:21:04,679 INFO] core.manager.schains - MainThread - sChain whispering-becrux successfully created
[2020-12-21 19:21:38,885 INFO] tools.testing_tools - MainThread - Waiting for successful DKG 600s...
[2020-12-21 19:24:10,418 INFO] core.manager.ima - MainThread - Registering sChain whispering-becrux on IMA...
[2020-12-21 19:24:10,419 INFO] skale.skale_base - MainThread - Initing skale.py, endpoint: http://15.236.104.23:8545, wallet: Web3Wallet
[2020-12-21 19:24:10,452 INFO] skale.transactions.tools - MainThread - Dry run tx: addSchain, sender: 0xA9C3F6D35fE2BeDf4DdA3B8f9625cf0652AEbEAa, wallet: Web3Wallet, 
[2020-12-21 19:24:10,699 INFO] skale.transactions.tools - MainThread - Estimated gas for addSchain: 131486
[2020-12-21 19:24:10,770 INFO] skale.transactions.tools - MainThread - Tx: addSchain, sender: 0xA9C3F6D35fE2BeDf4DdA3B8f9625cf0652AEbEAa, wallet: Web3Wallet, gasLimit: 131486, gasPrice: 5000000000
[2020-12-21 19:25:03,829 INFO] tools.checks - MainThread - Wait successful check_schain_alive for 40s ...
[2020-12-21 19:25:54,519 INFO] tools.checks - MainThread - ✔ check_schain_alive is succeed
[2020-12-21 19:25:54,519 INFO] core.infrastructure.instances - MainThread - Node: 34.244.197.165 - Stopping skale_schain_whispering-becrux container...
[2020-12-21 19:26:26,552 INFO] core.infrastructure.instances - MainThread - Node: 34.244.96.30 - Stopping skale_schain_whispering-becrux container...
[2020-12-21 19:26:58,964 INFO] core.infrastructure.instances - MainThread - Node: 3.249.163.173 - Stopping skale_schain_whispering-becrux container...
[2020-12-21 19:27:30,902 INFO] core.infrastructure.instances - MainThread - Node: 3.248.233.34 - Stopping skale_schain_whispering-becrux container...
[2020-12-21 19:27:45,462 INFO] core.infrastructure.instances - MainThread - Node: 34.248.12.186 - Stopping skale_schain_whispering-becrux container...
[2020-12-21 19:28:17,454 INFO] core.infrastructure.instances - MainThread - Node: 3.248.204.16 - Stopping skale_schain_whispering-becrux container...
[2020-12-21 19:28:35,473 INFO] tests.schains_tests - MainThread - Less than minimum sufficient amount of nodes is working
[2020-12-21 19:29:14,504 INFO] tests.schains_tests - MainThread - ✔ sChain RPC is working
[2020-12-21 19:29:14,504 INFO] tests.schains_tests - MainThread - Sleep 120s
[2020-12-21 19:31:14,565 INFO] core.infrastructure.instances - MainThread - Node: 3.248.204.16 - Restarting skale_schain_whispering-becrux container...
[2020-12-21 19:31:56,112 INFO] tools.checks - MainThread - ✔ check_schain_alive is succeed
[2020-12-21 19:32:29,397 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 0s ...
[2020-12-21 19:32:39,575 INFO] tools.checks - MainThread - Wait successful check_for_new_blocks for 10s ...Issue reproducing

**Comment by cstrangedk** [comment]
➤ Ganna Kulikova commented:

Stan Kladko  could you please have a look
